### ISSUE TITLE
[Emergency] Uncaught Error: Call to a member function getCollector() on bool

### ISSUE THREAD

**Issue by TheBnl** [lekoala/silverstripe-debugbar#132]
Hi,

This error keeps coming up in the CMS 4.7.1, after a refresh of the page the error is gone.

```
[Emergency] Uncaught Error: Call to a member function getCollector() on bool
GET /admin/catalog/
Line 573 in /home/vagrant/Sites/plantenvoorplanten/httpdocs/vendor/lekoala/silverstripe-debugbar/code/DebugBar.php

Trace:
LeKoala\DebugBar\DebugBar::getMessageCollector()
SSViewerProxy.php:67
LeKoala\DebugBar\Proxy\SSViewerProxy->process(My\ModelAdmin\Class)
ViewableData.php:401
```

Do you have any idea if this is a configuration issue?
I'm using the following config:

```yml
LeKoala\DebugBar\DebugBar:
  check_local_ip: false
  enabled_in_admin: false # maybe this setting is ingored somewhere?
```
